# Generated by Django 2.2.5 on 2020-06-17 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeboards', '0002_freeboard_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeboard',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
