# Generated by Django 2.2.5 on 2020-06-17 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freeboards', '0003_auto_20200617_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='freeboards.FreeBoard')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='freeboard',
            name='comment',
            field=models.ManyToManyField(blank=True, to='freeboards.Comment'),
        ),
    ]
