# Generated by Django 2.2.5 on 2020-05-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
